// Generated by tools/generate_birthplace_presets.py. Do not edit manually.
package com.agc.bwitch.ui.astrology.birthplace

import com.agc.bwitch.domain.astrology.natal.BirthplacePreset

internal val GeneratedBirthplacePresets: List<BirthplacePreset> = listOf(
)
