#!/usr/bin/env python3
"""Generate offline birthplace presets from a local GeoNames cities15000.txt file.

This tool intentionally performs no network access. Download GeoNames data manually,
then pass the local cities15000.txt path to this script.
"""

from __future__ import annotations

import argparse
import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path

DEFAULT_OUTPUT = Path(
    "composeApp/src/commonMain/kotlin/com/agc/bwitch/ui/astrology/birthplace/BirthplacePresets.generated.kt"
)
PACKAGE_NAME = "com.agc.bwitch.ui.astrology.birthplace"


@dataclass(frozen=True)
class City:
    geoname_id: str
    name: str
    country_code: str
    country_name: str
    latitude: str
    longitude: str
    timezone_id: str
    population: int


def parse_country_info(path: Path | None) -> dict[str, str]:
    if path is None:
        return {}
    countries: dict[str, str] = {}
    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            columns = line.split("\t")
            if len(columns) > 4 and columns[0]:
                countries[columns[0]] = columns[4]
    return countries


def parse_population(value: str, line_number: int) -> int:
    if not value.strip():
        return 0
    try:
        return int(value)
    except ValueError as exc:
        raise ValueError(f"Invalid population at line {line_number}: {value!r}") from exc


def parse_cities(path: Path, countries: dict[str, str], min_population: int | None) -> list[City]:
    cities: list[City] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.rstrip("\n")
            if not line:
                continue
            columns = line.split("\t")
            if len(columns) < 19:
                raise ValueError(
                    f"Invalid cities15000 row at line {line_number}: expected at least 19 columns"
                )
            geoname_id = columns[0].strip()
            name = columns[1].strip()
            latitude = columns[4].strip()
            longitude = columns[5].strip()
            country_code = columns[8].strip().upper()
            population = parse_population(columns[14], line_number)
            timezone_id = columns[17].strip()
            if min_population is not None and population < min_population:
                continue
            if not (geoname_id and name and latitude and longitude and country_code and timezone_id):
                continue
            cities.append(
                City(
                    geoname_id=geoname_id,
                    name=name,
                    country_code=country_code,
                    country_name=countries.get(country_code, country_code),
                    latitude=latitude,
                    longitude=longitude,
                    timezone_id=timezone_id,
                    population=population,
                )
            )
    return sorted(
        cities,
        key=lambda city: (city.country_name.casefold(), city.name.casefold(), city.geoname_id),
    )


def slug(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    normalized = normalized.lower().replace("&", " and ")
    normalized = re.sub(r"[^a-z0-9]+", "-", normalized)
    return normalized.strip("-") or "city"


def kt_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def limit_by_population(cities: list[City], limit: int | None) -> list[City]:
    if limit is None:
        return cities
    top_cities = sorted(
        cities,
        key=lambda city: (
            -city.population,
            city.country_name.casefold(),
            city.name.casefold(),
            city.geoname_id,
        ),
    )[:limit]
    return sorted(
        top_cities,
        key=lambda city: (city.country_name.casefold(), city.name.casefold(), city.geoname_id),
    )


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("value must be greater than 0")
    return parsed


def render(cities: list[City]) -> str:
    lines = [
        "// Generated by tools/generate_birthplace_presets.py. Do not edit manually.",
        f"package {PACKAGE_NAME}",
        "",
        "import com.agc.bwitch.domain.astrology.natal.BirthplacePreset",
        "",
        "internal val GeneratedBirthplacePresets: List<BirthplacePreset> = listOf(",
    ]
    for city in cities:
        preset_id = f"{slug(city.name)}-{city.country_code.lower()}-{city.geoname_id}"
        lines.append(
            "    BirthplacePreset("
            f"id = {kt_string(preset_id)}, "
            f"cityName = {kt_string(city.name)}, "
            f"countryName = {kt_string(city.country_name)}, "
            f"latitudeDegrees = {city.latitude}, "
            f"longitudeDegrees = {city.longitude}, "
            f"timezoneId = {kt_string(city.timezone_id)}, "
            f"countryCode = {kt_string(city.country_code)}"
            "),"
        )
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate KMP birthplace presets from local GeoNames cities15000.txt."
    )
    parser.add_argument("cities15000", type=Path, help="Path to a local GeoNames cities15000.txt file")
    parser.add_argument(
        "--country-info",
        type=Path,
        default=None,
        help="Optional local GeoNames countryInfo.txt for country names",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output Kotlin file (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--min-population",
        type=positive_int,
        default=None,
        help="Only include cities with at least this GeoNames population value",
    )
    parser.add_argument(
        "--limit",
        type=positive_int,
        default=None,
        help="Keep only the top N cities by population before final deterministic sorting",
    )
    args = parser.parse_args()

    countries = parse_country_info(args.country_info)
    cities = limit_by_population(
        parse_cities(args.cities15000, countries, args.min_population),
        args.limit,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(cities), encoding="utf-8")
    print(f"Generated {len(cities)} birthplace presets at {args.output}")


if __name__ == "__main__":
    main()
