package com.agc.bwitch.localization

import com.agc.bwitch.domain.localization.AppLanguage

data class AppStrings(
    val auth: AuthStrings,
    val onboarding: OnboardingStrings,
    val settings: SettingsStrings,
    val navigation: NavigationStrings,
    val common: CommonStrings,
    val profile: ProfileStrings,
    val astrologyHome: AstrologyHomeStrings,
    val birthChart: BirthChartStrings,
    val horoscope: HoroscopeStrings,
    val synastry: SynastryStrings,
    val zodiac: ZodiacStrings,
)

data class AuthStrings(
    val subtitle: String,
    val continueWithGoogle: String,
    val emailLabel: String,
    val passwordLabel: String,
    val signIn: String,
    val signUp: String,
    val connecting: String,
    val googleSignInErrorFallback: String,
)

data class OnboardingStrings(
    val profileTitle: String,
    val profileSubtitle: String,
    val profileAvatarContentDescription: String,
    val usernameLabel: String,
    val usernameError: String,
    val birthDateLabel: String,
    val birthDatePlaceholder: String,
    val birthDateFormatError: String,
    val continueButton: String,
)

data class SettingsStrings(
    val subtitle: String,
    val refreshProfile: String,
    val signOut: String,
)

data class NavigationStrings(
    val onboardingProfile: String,
    val astrology: String,
    val birthChart: String,
    val synastry: String,
    val profile: String,
    val settings: String,
    val oracle: String,
    val oracleDebug: String,
    val guide: String,
    val rituals: String,
    val ritual: String,
    val dailyRitual: String,
    val habits: String,
    val tarot: String,
    val pendulum: String,
    val horoscopeDaily: String,
)

data class CommonStrings(
    val languageSectionTitle: String,
    val languageSectionSubtitle: String,
    val languageSelectedPrefix: String,
)

data class ProfileStrings(
    val defaultUsername: String,
    val pendingSign: String,
    val avatarContentDescription: String,
    val moonCreditsTitle: String,
    val storeLabel: String,
    val storeSoon: String,
    val storeOpen: String,
    val birthEssenceTitle: String,
    val birthEssenceEmpty: String,
    val birthEssenceSunLabel: String,
    val birthEssenceMoonLabel: String,
    val birthEssenceAscLabel: String,
    val progressTitle: String,
    val progressSubtitle: String,
    val completedCyclesSuffix: String,
    val progressNotStarted: String,
    val openHabits: String,
    val archetypeLabel: String,
    val birthEssenceDialogClose: String,
    val birthEssenceVisualContentDescriptionPrefix: String,
)

data class AstrologyHomeStrings(
    val headerTitle: String,
    val headerSubtitle: String,
    val horoscopeCardTitle: String,
    val horoscopeCardSubtitle: String,
    val birthEssenceCardTitle: String,
    val birthEssenceCardSubtitle: String,
    val synastryCardTitle: String,
    val synastryCardSubtitle: String,
)

data class BirthChartStrings(
    val title: String,
    val subtitle: String,
    val sunSignLabel: String,
    val moonSignLabel: String,
    val risingSignLabel: String,
    val discoverLoading: String,
    val discoverCta: String,
    val triadTitle: String,
    val triadSunLabel: String,
    val triadMoonLabel: String,
    val triadAscLabel: String,
    val archetypeLabel: String,
    val saveLoading: String,
    val saveCta: String,
    val shareValidationError: String,
    val shareCta: String,
    val syncLoading: String,
    val syncCta: String,
    val sharePreviewTitle: String,
    val shareNowCta: String,
    val shareCancelCta: String,
    val shareFailedFallback: String,
    val archetypeVisualContentDescriptionPrefix: String,
)

data class HoroscopeStrings(
    val refreshLoading: String,
    val loading: String,
    val refreshCta: String,
    val alreadyUpdatedMessage: String,
    val updatedMessage: String,
    val refreshErrorMessage: String,
    val dateLabel: String,
    val moodLabel: String,
    val luckyNumberLabel: String,
    val luckyColorLabel: String,
)

data class SynastryStrings(
    val screenTitle: String,
    val screenSubtitle: String,
    val screenSupportingText: String,
    val calculateCta: String,
    val calculatingCta: String,
    val resultTitle: String,
    val bondMetricsTitle: String,
    val dailyEnergyTitle: String,
    val strengthTitle: String,
    val tensionTitle: String,
    val guidanceTitle: String,
    val dailyGuidanceTitle: String,
    val narrativeTitle: String,
    val cardALabel: String,
    val cardBLabel: String,
    val sunSignLabel: String,
    val moonLabel: String,
    val risingLabel: String,
    val selectPlaceholder: String,
    val unspecifiedOption: String,
    val closeCta: String,
    val requiredSunSignsError: String,
    val genericGenerateError: String,
    val depthBasic: String,
    val depthPartial: String,
    val depthComplete: String,
    val dimensionAttraction: String,
    val dimensionEmotional: String,
    val dimensionCommunication: String,
    val dimensionGrowth: String,
    val axisHarmony: String,
    val axisIntensity: String,
    val axisStability: String,
    val axisTransformation: String,
    val axisCalm: String,
    val axisMovement: String,
    val axisHarmonyIntensityTitle: String,
    val axisHarmonyIntensityDescription: String,
    val axisStabilityTransformationTitle: String,
    val axisStabilityTransformationDescription: String,
    val axisCalmMovementTitle: String,
    val axisCalmMovementDescription: String,
)

data class ZodiacStrings(
    val aries: String,
    val taurus: String,
    val gemini: String,
    val cancer: String,
    val leo: String,
    val virgo: String,
    val libra: String,
    val scorpio: String,
    val sagittarius: String,
    val capricorn: String,
    val aquarius: String,
    val pisces: String,
)

fun resolveAppStrings(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.Spanish -> fallbackAppStrings
    AppLanguage.English -> englishAppStrings
    AppLanguage.Portuguese -> portugueseAppStrings
    AppLanguage.Russian -> russianAppStrings
    AppLanguage.French -> frenchAppStrings
    AppLanguage.Italian -> italianAppStrings
    AppLanguage.German -> germanAppStrings
}

val fallbackAppStrings: AppStrings = AppStrings(
    auth = AuthStrings(
        subtitle = "Accede para continuar tu camino mágico",
        continueWithGoogle = "Continuar con Google",
        emailLabel = "Correo electrónico",
        passwordLabel = "Contraseña",
        signIn = "Iniciar sesión",
        signUp = "Crear cuenta",
        connecting = "Conectando…",
        googleSignInErrorFallback = "No se pudo iniciar sesión con Google",
    ),
    onboarding = OnboardingStrings(
        profileTitle = "Completa tu perfil",
        profileSubtitle = "Necesitamos algunos datos para personalizar tu experiencia.",
        profileAvatarContentDescription = "Avatar del perfil",
        usernameLabel = "Nombre de usuario",
        usernameError = "Usa entre 3 y 20 caracteres: letras, números, punto o guion bajo.",
        birthDateLabel = "Fecha de nacimiento",
        birthDatePlaceholder = "AAAA-MM-DD",
        birthDateFormatError = "Formato inválido. Usa AAAA-MM-DD.",
        continueButton = "Continuar",
    ),
    settings = SettingsStrings(
        subtitle = "Gestiona tu perfil y preferencias",
        refreshProfile = "Actualizar perfil",
        signOut = "Cerrar sesión",
    ),
    navigation = NavigationStrings(
        onboardingProfile = "Completa tu perfil",
        astrology = "Astrología",
        birthChart = "Esencia natal",
        synastry = "Sinastría",
        profile = "Perfil",
        settings = "Ajustes",
        oracle = "Oráculo",
        oracleDebug = "Oracle debug",
        guide = "Guía",
        rituals = "Rituales",
        ritual = "Ritual",
        dailyRitual = "Ritual del día",
        habits = "Hábitos",
        tarot = "Tarot",
        pendulum = "El Péndulo",
        horoscopeDaily = "Horóscopo diario",
    ),
    common = CommonStrings(
        languageSectionTitle = "Idioma de la app",
        languageSectionSubtitle = "Este cambio se aplicará en próximas pantallas migradas.",
        languageSelectedPrefix = "✓ ",
    ),
    profile = ProfileStrings(
        defaultUsername = "perfil",
        pendingSign = "Signo pendiente",
        avatarContentDescription = "Avatar de perfil",
        moonCreditsTitle = "Lunas",
        storeLabel = "Tienda",
        storeSoon = "Pronto",
        storeOpen = "Abrir",
        birthEssenceTitle = "Esencia natal",
        birthEssenceEmpty = "Aún no has vinculado tu esencia. Te acompañamos a descubrirla.",
        birthEssenceSunLabel = "SOL",
        birthEssenceMoonLabel = "LUNA",
        birthEssenceAscLabel = "ASC",
        progressTitle = "Tu progreso",
        progressSubtitle = "Cada pequeña práctica deja una huella en tu camino.",
        completedCyclesSuffix = "ciclos completados",
        progressNotStarted = "Aún no has comenzado este ciclo. Completa una práctica en Hábitos para dar el primer paso.",
        openHabits = "Abrir Hábitos",
        archetypeLabel = "Arquetipo",
        birthEssenceDialogClose = "Cerrar",
        birthEssenceVisualContentDescriptionPrefix = "Visual",
    ),
    astrologyHome = AstrologyHomeStrings(
        headerTitle = "Tu cielo interior",
        headerSubtitle = "Explora tu esencia y los ritmos que te acompañan",
        horoscopeCardTitle = "Horóscopo",
        horoscopeCardSubtitle = "Tu energía de hoy… y lo que viene",
        birthEssenceCardTitle = "Esencia natal",
        birthEssenceCardSubtitle = "La huella de tu nacimiento",
        synastryCardTitle = "Sinastría",
        synastryCardSubtitle = "La energía entre dos",
    ),
    birthChart = BirthChartStrings(
        title = "Esencia natal",
        subtitle = "Selecciona Sol, Luna y Ascendente para recibir una lectura breve estilo BWitch.",
        sunSignLabel = "Signo solar",
        moonSignLabel = "Signo lunar",
        risingSignLabel = "Ascendente",
        discoverLoading = "Descubriendo...",
        discoverCta = "Descubrir mi esencia",
        triadTitle = "Tu triada",
        triadSunLabel = "Sol",
        triadMoonLabel = "Luna",
        triadAscLabel = "Asc",
        archetypeLabel = "Arquetipo",
        saveLoading = "Guardando...",
        saveCta = "Guardar en mi perfil",
        shareValidationError = "Primero genera una esencia válida",
        shareCta = "Compartir esencia",
        syncLoading = "Sincronizando...",
        syncCta = "Sincronizar",
        sharePreviewTitle = "Preview para compartir",
        shareNowCta = "Compartir ahora",
        shareCancelCta = "Cancelar",
        shareFailedFallback = "No se pudo compartir la esencia",
        archetypeVisualContentDescriptionPrefix = "Visual",
    ),
    horoscope = HoroscopeStrings(
        refreshLoading = "Actualizando...",
        loading = "Cargando...",
        refreshCta = "Actualizar",
        alreadyUpdatedMessage = "Ya está actualizado",
        updatedMessage = "Actualizado",
        refreshErrorMessage = "No se pudo actualizar el horóscopo",
        dateLabel = "Fecha",
        moodLabel = "Mood",
        luckyNumberLabel = "Número de la suerte",
        luckyColorLabel = "Color de la suerte",
    ),
    synastry = SynastryStrings(
        screenTitle = "Sinastría",
        screenSubtitle = "Explora la dinámica entre dos signos y descubre qué áreas del vínculo se activan con más fuerza.",
        screenSupportingText = "La lectura combina afinidad simbólica entre signos con un matiz energético diario del momento.",
        calculateCta = "Calcular lectura",
        calculatingCta = "Calculando...",
        resultTitle = "Resultado",
        bondMetricsTitle = "MÉTRICAS DEL VÍNCULO",
        dailyEnergyTitle = "ENERGÍA DEL DÍA",
        strengthTitle = "FORTALEZA",
        tensionTitle = "TENSIÓN",
        guidanceTitle = "GUÍA",
        dailyGuidanceTitle = "CONSEJO DEL DÍA",
        narrativeTitle = "NARRATIVA",
        cardALabel = "Carta A",
        cardBLabel = "Carta B",
        sunSignLabel = "☀ Signo solar",
        moonLabel = "🌙 Luna",
        risingLabel = "⤴ Ascendente",
        selectPlaceholder = "Seleccionar",
        unspecifiedOption = "No especificar",
        closeCta = "Cerrar",
        requiredSunSignsError = "El signo solar es obligatorio para ambas personas",
        genericGenerateError = "No se pudo generar la lectura de sinastría",
        depthBasic = "Lectura esencial",
        depthPartial = "Lectura ampliada",
        depthComplete = "Lectura completa",
        dimensionAttraction = "Atracción",
        dimensionEmotional = "Sintonía emocional",
        dimensionCommunication = "Comunicación",
        dimensionGrowth = "Potencial de crecimiento",
        axisHarmony = "Armonía",
        axisIntensity = "Intensidad",
        axisStability = "Estabilidad",
        axisTransformation = "Transformación",
        axisCalm = "Calma",
        axisMovement = "Movimiento",
        axisHarmonyIntensityTitle = "Armonía ↔ Intensidad",
        axisHarmonyIntensityDescription = "Mide si hoy el vínculo fluye desde equilibrio y facilidad, o desde una chispa emocional más intensa.",
        axisStabilityTransformationTitle = "Estabilidad ↔ Transformación",
        axisStabilityTransformationDescription = "Indica si la energía del día favorece sostener lo construido o abrir cambios y redefinir acuerdos.",
        axisCalmMovementTitle = "Calma ↔ Movimiento",
        axisCalmMovementDescription = "Refleja si conviene priorizar pausa y contención, o activar más movimiento, iniciativa y acción compartida.",
    ),
    zodiac = ZodiacStrings(
        aries = "Aries",
        taurus = "Tauro",
        gemini = "Géminis",
        cancer = "Cáncer",
        leo = "Leo",
        virgo = "Virgo",
        libra = "Libra",
        scorpio = "Escorpio",
        sagittarius = "Sagitario",
        capricorn = "Capricornio",
        aquarius = "Acuario",
        pisces = "Piscis",
    ),
)

private val englishAppStrings = fallbackAppStrings.copy(
    auth = fallbackAppStrings.auth.copy(
        subtitle = "Sign in to continue your magical path",
        continueWithGoogle = "Continue with Google",
        emailLabel = "Email",
        passwordLabel = "Password",
        signIn = "Sign in",
        signUp = "Create account",
        connecting = "Connecting…",
        googleSignInErrorFallback = "Google sign-in failed",
    ),
    onboarding = fallbackAppStrings.onboarding.copy(
        profileTitle = "Complete your profile",
        profileSubtitle = "We need a few details to personalize your experience.",
        profileAvatarContentDescription = "Profile avatar",
        usernameLabel = "Username",
        usernameError = "Use 3 to 20 characters: letters, numbers, dot or underscore.",
        birthDateLabel = "Birth date",
        birthDatePlaceholder = "YYYY-MM-DD",
        birthDateFormatError = "Invalid format. Use YYYY-MM-DD.",
        continueButton = "Continue",
    ),
    settings = fallbackAppStrings.settings.copy(
        subtitle = "Manage your profile and preferences",
        refreshProfile = "Refresh profile",
        signOut = "Sign out",
    ),
    navigation = fallbackAppStrings.navigation.copy(
        onboardingProfile = "Complete your profile",
        astrology = "Astrology",
        birthChart = "Birth essence",
        synastry = "Synastry",
        profile = "Profile",
        settings = "Settings",
        oracle = "Oracle",
        guide = "Guide",
        rituals = "Rituals",
        ritual = "Ritual",
        dailyRitual = "Daily ritual",
        habits = "Habits",
        pendulum = "Pendulum",
        horoscopeDaily = "Daily horoscope",
    ),
    common = fallbackAppStrings.common.copy(
        languageSectionTitle = "App language",
        languageSectionSubtitle = "This change will apply to migrated screens.",
    ),
    profile = fallbackAppStrings.profile.copy(
        defaultUsername = "profile",
        pendingSign = "Sign pending",
        avatarContentDescription = "Profile avatar",
        moonCreditsTitle = "Moons",
        storeLabel = "Store",
        storeSoon = "Soon",
        storeOpen = "Open",
        birthEssenceTitle = "Birth essence",
        birthEssenceEmpty = "You have not linked your essence yet. We can help you discover it.",
        birthEssenceSunLabel = "SUN",
        birthEssenceMoonLabel = "MOON",
        birthEssenceAscLabel = "ASC",
        progressTitle = "Your progress",
        progressSubtitle = "Each little practice leaves a trace on your path.",
        completedCyclesSuffix = "completed cycles",
        progressNotStarted = "You have not started this cycle yet. Complete a Habits practice to take your first step.",
        openHabits = "Open Habits",
        archetypeLabel = "Archetype",
        birthEssenceDialogClose = "Close",
        birthEssenceVisualContentDescriptionPrefix = "Visual",
    ),
    astrologyHome = fallbackAppStrings.astrologyHome.copy(
        headerTitle = "Your inner sky",
        headerSubtitle = "Explore your essence and the rhythms that guide you",
        horoscopeCardTitle = "Horoscope",
        horoscopeCardSubtitle = "Your energy for today… and what comes next",
        birthEssenceCardTitle = "Birth essence",
        birthEssenceCardSubtitle = "The imprint of your birth",
        synastryCardTitle = "Synastry",
        synastryCardSubtitle = "The energy between two",
    ),
    birthChart = fallbackAppStrings.birthChart.copy(
        title = "Birth essence",
        subtitle = "Choose Sun, Moon and Rising to receive a short BWitch-style reading.",
        sunSignLabel = "Sun sign",
        moonSignLabel = "Moon sign",
        risingSignLabel = "Rising sign",
        discoverLoading = "Discovering...",
        discoverCta = "Discover my essence",
        triadTitle = "Your triad",
        triadSunLabel = "Sun",
        triadMoonLabel = "Moon",
        triadAscLabel = "Asc",
        archetypeLabel = "Archetype",
        saveLoading = "Saving...",
        saveCta = "Save to my profile",
        shareValidationError = "Generate a valid essence first",
        shareCta = "Share essence",
        syncLoading = "Syncing...",
        syncCta = "Sync",
        sharePreviewTitle = "Share preview",
        shareNowCta = "Share now",
        shareCancelCta = "Cancel",
        shareFailedFallback = "Could not share essence",
        archetypeVisualContentDescriptionPrefix = "Visual",
    ),
    horoscope = fallbackAppStrings.horoscope.copy(
        refreshLoading = "Refreshing...",
        loading = "Loading...",
        refreshCta = "Refresh",
        alreadyUpdatedMessage = "Already up to date",
        updatedMessage = "Updated",
        refreshErrorMessage = "Could not refresh the horoscope",
        dateLabel = "Date",
        moodLabel = "Mood",
        luckyNumberLabel = "Lucky number",
        luckyColorLabel = "Lucky color",
    ),
    synastry = fallbackAppStrings.synastry.copy(
        screenTitle = "Synastry",
        screenSubtitle = "Explore the dynamic between two signs and discover which bond areas are most activated.",
        screenSupportingText = "The reading combines symbolic sign affinity with the current daily energetic tone.",
        calculateCta = "Calculate reading",
        calculatingCta = "Calculating...",
        resultTitle = "Result",
        bondMetricsTitle = "BOND METRICS",
        dailyEnergyTitle = "DAILY ENERGY",
        strengthTitle = "STRENGTH",
        tensionTitle = "TENSION",
        guidanceTitle = "GUIDANCE",
        dailyGuidanceTitle = "DAILY GUIDANCE",
        narrativeTitle = "NARRATIVE",
        cardALabel = "Chart A",
        cardBLabel = "Chart B",
        sunSignLabel = "☀ Sun sign",
        moonLabel = "🌙 Moon",
        risingLabel = "⤴ Rising",
        selectPlaceholder = "Select",
        unspecifiedOption = "Unspecified",
        closeCta = "Close",
        requiredSunSignsError = "Sun sign is required for both people",
        genericGenerateError = "Could not generate synastry reading",
        depthBasic = "Essential reading",
        depthPartial = "Expanded reading",
        depthComplete = "Complete reading",
        dimensionAttraction = "Attraction",
        dimensionEmotional = "Emotional resonance",
        dimensionCommunication = "Communication",
        dimensionGrowth = "Growth potential",
        axisHarmony = "Harmony",
        axisIntensity = "Intensity",
        axisStability = "Stability",
        axisTransformation = "Transformation",
        axisCalm = "Calm",
        axisMovement = "Movement",
        axisHarmonyIntensityTitle = "Harmony ↔ Intensity",
        axisHarmonyIntensityDescription = "Shows whether the bond flows from balance and ease, or from a stronger emotional spark today.",
        axisStabilityTransformationTitle = "Stability ↔ Transformation",
        axisStabilityTransformationDescription = "Indicates whether today favors sustaining what is built or opening change and redefining agreements.",
        axisCalmMovementTitle = "Calm ↔ Movement",
        axisCalmMovementDescription = "Reflects whether to prioritize pause and containment, or activate more movement and shared initiative.",
    ),
    zodiac = fallbackAppStrings.zodiac.copy(
        taurus = "Taurus",
        gemini = "Gemini",
        cancer = "Cancer",
        virgo = "Virgo",
        libra = "Libra",
        scorpio = "Scorpio",
        sagittarius = "Sagittarius",
        capricorn = "Capricorn",
        aquarius = "Aquarius",
        pisces = "Pisces",
    ),
)

private val portugueseAppStrings = fallbackAppStrings.copy(
    auth = fallbackAppStrings.auth.copy(
        subtitle = "Entre para continuar seu caminho mágico",
        continueWithGoogle = "Continuar com Google",
        emailLabel = "E-mail",
        passwordLabel = "Senha",
        signIn = "Entrar",
        signUp = "Criar conta",
        connecting = "Conectando…",
        googleSignInErrorFallback = "Não foi possível entrar com o Google",
    ),
    onboarding = fallbackAppStrings.onboarding.copy(
        profileTitle = "Complete seu perfil",
        profileSubtitle = "Precisamos de alguns dados para personalizar sua experiência.",
        profileAvatarContentDescription = "Avatar do perfil",
        usernameLabel = "Nome de usuário",
        usernameError = "Use de 3 a 20 caracteres: letras, números, ponto ou sublinhado.",
        birthDateLabel = "Data de nascimento",
        birthDatePlaceholder = "AAAA-MM-DD",
        birthDateFormatError = "Formato inválido. Use AAAA-MM-DD.",
        continueButton = "Continuar",
    ),
    settings = fallbackAppStrings.settings.copy(
        subtitle = "Gerencie seu perfil e preferências",
        refreshProfile = "Atualizar perfil",
        signOut = "Sair",
    ),
    navigation = fallbackAppStrings.navigation.copy(
        onboardingProfile = "Complete seu perfil",
        astrology = "Astrologia",
        birthChart = "Essência natal",
        synastry = "Sinastria",
        profile = "Perfil",
        settings = "Configurações",
        oracle = "Oráculo",
        guide = "Guia",
        rituals = "Rituais",
        dailyRitual = "Ritual do dia",
        habits = "Hábitos",
        pendulum = "Pêndulo",
        horoscopeDaily = "Horóscopo diário",
    ),
    common = fallbackAppStrings.common.copy(
        languageSectionTitle = "Idioma do app",
        languageSectionSubtitle = "Esta mudança será aplicada nas telas migradas.",
    ),
    profile = fallbackAppStrings.profile.copy(
        defaultUsername = "perfil",
        pendingSign = "Signo pendente",
        avatarContentDescription = "Avatar do perfil",
        moonCreditsTitle = "Luas",
        storeSoon = "Em breve",
        storeOpen = "Abrir",
        birthEssenceEmpty = "Você ainda não vinculou sua essência. Vamos te ajudar a descobri-la.",
        progressTitle = "Seu progresso",
        progressSubtitle = "Cada pequena prática deixa uma marca no seu caminho.",
        completedCyclesSuffix = "ciclos concluídos",
        progressNotStarted = "Você ainda não começou este ciclo. Complete uma prática em Hábitos para dar o primeiro passo.",
        openHabits = "Abrir Hábitos",
        birthEssenceDialogClose = "Fechar",
    ),
    astrologyHome = fallbackAppStrings.astrologyHome.copy(
        headerTitle = "Seu céu interior",
        headerSubtitle = "Explore sua essência e os ritmos que te acompanham",
        horoscopeCardTitle = "Horóscopo",
        horoscopeCardSubtitle = "Sua energia de hoje… e o que vem depois",
        birthEssenceCardTitle = "Essência natal",
        birthEssenceCardSubtitle = "A marca do seu nascimento",
        synastryCardTitle = "Sinastria",
        synastryCardSubtitle = "A energia entre duas pessoas",
    ),
    birthChart = fallbackAppStrings.birthChart.copy(
        title = "Essência natal",
        subtitle = "Selecione Sol, Lua e Ascendente para receber uma leitura breve no estilo BWitch.",
        sunSignLabel = "Signo solar",
        moonSignLabel = "Signo lunar",
        discoverLoading = "Descobrindo...",
        discoverCta = "Descobrir minha essência",
        triadTitle = "Sua tríade",
        triadAscLabel = "Asc",
        saveLoading = "Salvando...",
        saveCta = "Salvar no meu perfil",
        shareValidationError = "Primeiro gere uma essência válida",
        shareCta = "Compartilhar essência",
        syncLoading = "Sincronizando...",
        syncCta = "Sincronizar",
        sharePreviewTitle = "Prévia para compartilhar",
        shareNowCta = "Compartilhar agora",
        shareCancelCta = "Cancelar",
        shareFailedFallback = "Não foi possível compartilhar a essência",
    ),
    horoscope = fallbackAppStrings.horoscope.copy(
        refreshLoading = "Atualizando...",
        loading = "Carregando...",
        refreshCta = "Atualizar",
        alreadyUpdatedMessage = "Já está atualizado",
        updatedMessage = "Atualizado",
        refreshErrorMessage = "Não foi possível atualizar o horóscopo",
        dateLabel = "Data",
        luckyNumberLabel = "Número da sorte",
        luckyColorLabel = "Cor da sorte",
    ),
    synastry = fallbackAppStrings.synastry.copy(
        screenTitle = "Sinastria",
        screenSubtitle = "Explore a dinâmica entre dois signos e descubra quais áreas do vínculo estão mais ativas.",
        screenSupportingText = "A leitura combina afinidade simbólica entre signos com o tom energético diário do momento.",
        calculateCta = "Calcular leitura",
        calculatingCta = "Calculando...",
        resultTitle = "Resultado",
        bondMetricsTitle = "MÉTRICAS DO VÍNCULO",
        dailyEnergyTitle = "ENERGIA DO DIA",
        strengthTitle = "FORÇA",
        tensionTitle = "TENSÃO",
        guidanceTitle = "GUIA",
        dailyGuidanceTitle = "CONSELHO DO DIA",
        narrativeTitle = "NARRATIVA",
        cardALabel = "Mapa A",
        cardBLabel = "Mapa B",
        sunSignLabel = "☀ Signo solar",
        moonLabel = "🌙 Lua",
        risingLabel = "⤴ Ascendente",
        selectPlaceholder = "Selecionar",
        unspecifiedOption = "Não especificar",
        closeCta = "Fechar",
        requiredSunSignsError = "O signo solar é obrigatório para ambas as pessoas",
        genericGenerateError = "Não foi possível gerar a leitura de sinastria",
        depthBasic = "Leitura essencial",
        depthPartial = "Leitura ampliada",
        depthComplete = "Leitura completa",
        dimensionAttraction = "Atração",
        dimensionEmotional = "Sintonia emocional",
        dimensionCommunication = "Comunicação",
        dimensionGrowth = "Potencial de crescimento",
        axisHarmony = "Harmonia",
        axisIntensity = "Intensidade",
        axisStability = "Estabilidade",
        axisTransformation = "Transformação",
        axisCalm = "Calma",
        axisMovement = "Movimento",
        axisHarmonyIntensityTitle = "Harmonia ↔ Intensidade",
        axisHarmonyIntensityDescription = "Mostra se hoje o vínculo flui com equilíbrio e leveza, ou com uma faísca emocional mais intensa.",
        axisStabilityTransformationTitle = "Estabilidade ↔ Transformação",
        axisStabilityTransformationDescription = "Indica se a energia do dia favorece sustentar o que foi construído ou abrir mudanças e redefinir acordos.",
        axisCalmMovementTitle = "Calma ↔ Movimento",
        axisCalmMovementDescription = "Reflete se convém priorizar pausa e contenção, ou ativar mais movimento e iniciativa compartilhada.",
    ),
    zodiac = fallbackAppStrings.zodiac.copy(
        taurus = "Touro",
        gemini = "Gêmeos",
        cancer = "Câncer",
        libra = "Libra",
        scorpio = "Escorpião",
        sagittarius = "Sagitário",
        capricorn = "Capricórnio",
        aquarius = "Aquário",
        pisces = "Peixes",
    ),
)

private val russianAppStrings = fallbackAppStrings.copy(
    auth = fallbackAppStrings.auth.copy(
        subtitle = "Войдите, чтобы продолжить ваш магический путь",
        continueWithGoogle = "Продолжить с Google",
        emailLabel = "Эл. почта",
        passwordLabel = "Пароль",
        signIn = "Войти",
        signUp = "Создать аккаунт",
        connecting = "Подключение…",
        googleSignInErrorFallback = "Не удалось войти через Google",
    ),
    onboarding = fallbackAppStrings.onboarding.copy(
        profileTitle = "Заполните профиль",
        profileSubtitle = "Нам нужны некоторые данные для персонализации.",
        profileAvatarContentDescription = "Аватар профиля",
        usernameLabel = "Имя пользователя",
        usernameError = "Используйте 3–20 символов: буквы, цифры, точка или подчеркивание.",
        birthDateLabel = "Дата рождения",
        birthDatePlaceholder = "ГГГГ-ММ-ДД",
        birthDateFormatError = "Неверный формат. Используйте ГГГГ-ММ-ДД.",
        continueButton = "Продолжить",
    ),
    settings = fallbackAppStrings.settings.copy(
        subtitle = "Управляйте профилем и настройками",
        refreshProfile = "Обновить профиль",
        signOut = "Выйти",
    ),
    navigation = fallbackAppStrings.navigation.copy(
        onboardingProfile = "Заполните профиль",
        astrology = "Астрология",
        birthChart = "Натальная сущность",
        synastry = "Синастрия",
        profile = "Профиль",
        settings = "Настройки",
        oracle = "Оракул",
        guide = "Гид",
        rituals = "Ритуалы",
        dailyRitual = "Ритуал дня",
        habits = "Привычки",
        pendulum = "Маятник",
        horoscopeDaily = "Ежедневный гороскоп",
    ),
    common = fallbackAppStrings.common.copy(
        languageSectionTitle = "Язык приложения",
        languageSectionSubtitle = "Изменение применится к уже мигрированным экранам.",
    ),
    profile = fallbackAppStrings.profile.copy(
        defaultUsername = "профиль",
        pendingSign = "Знак не выбран",
        avatarContentDescription = "Аватар профиля",
        moonCreditsTitle = "Луны",
        storeLabel = "Магазин",
        storeSoon = "Скоро",
        storeOpen = "Открыть",
        birthEssenceTitle = "Натальная сущность",
        birthEssenceEmpty = "Вы ещё не привязали свою сущность. Мы поможем её открыть.",
        birthEssenceSunLabel = "СОЛНЦЕ",
        birthEssenceMoonLabel = "ЛУНА",
        birthEssenceAscLabel = "АСЦ",
        progressTitle = "Ваш прогресс",
        progressSubtitle = "Каждая маленькая практика оставляет след на вашем пути.",
        completedCyclesSuffix = "завершённых циклов",
        progressNotStarted = "Вы ещё не начали этот цикл. Выполните практику в «Привычках», чтобы сделать первый шаг.",
        openHabits = "Открыть Привычки",
        archetypeLabel = "Архетип",
        birthEssenceDialogClose = "Закрыть",
        birthEssenceVisualContentDescriptionPrefix = "Образ",
    ),
    astrologyHome = fallbackAppStrings.astrologyHome.copy(
        headerTitle = "Ваш внутренний небосвод",
        headerSubtitle = "Исследуйте свою сущность и ритмы, которые вас сопровождают",
        horoscopeCardTitle = "Гороскоп",
        horoscopeCardSubtitle = "Ваша энергия на сегодня… и что дальше",
        birthEssenceCardTitle = "Натальная сущность",
        birthEssenceCardSubtitle = "Отпечаток вашего рождения",
        synastryCardTitle = "Синастрия",
        synastryCardSubtitle = "Энергия между двумя",
    ),
    birthChart = fallbackAppStrings.birthChart.copy(
        title = "Натальная сущность",
        subtitle = "Выберите Солнце, Луну и Асцендент, чтобы получить краткое чтение в стиле BWitch.",
        sunSignLabel = "Солнечный знак",
        moonSignLabel = "Лунный знак",
        risingSignLabel = "Асцендент",
        discoverLoading = "Открываем...",
        discoverCta = "Открыть мою сущность",
        triadTitle = "Ваша триада",
        triadSunLabel = "Солнце",
        triadMoonLabel = "Луна",
        triadAscLabel = "Асц",
        archetypeLabel = "Архетип",
        saveLoading = "Сохранение...",
        saveCta = "Сохранить в профиль",
        shareValidationError = "Сначала создайте корректную сущность",
        shareCta = "Поделиться сущностью",
        syncLoading = "Синхронизация...",
        syncCta = "Синхронизировать",
        sharePreviewTitle = "Предпросмотр для шаринга",
        shareNowCta = "Поделиться сейчас",
        shareCancelCta = "Отмена",
        shareFailedFallback = "Не удалось поделиться сущностью",
        archetypeVisualContentDescriptionPrefix = "Образ",
    ),
    horoscope = fallbackAppStrings.horoscope.copy(
        refreshLoading = "Обновление...",
        loading = "Загрузка...",
        refreshCta = "Обновить",
        alreadyUpdatedMessage = "Уже актуально",
        updatedMessage = "Обновлено",
        refreshErrorMessage = "Не удалось обновить гороскоп",
        dateLabel = "Дата",
        moodLabel = "Настроение",
        luckyNumberLabel = "Счастливое число",
        luckyColorLabel = "Счастливый цвет",
    ),
    synastry = fallbackAppStrings.synastry.copy(
        screenTitle = "Синастрия",
        screenSubtitle = "Исследуйте динамику между двумя знаками и узнайте, какие сферы связи активируются сильнее всего.",
        screenSupportingText = "Чтение сочетает символическую совместимость знаков с ежедневным энергетическим оттенком.",
        calculateCta = "Рассчитать чтение",
        calculatingCta = "Расчёт...",
        resultTitle = "Результат",
        bondMetricsTitle = "МЕТРИКИ СВЯЗИ",
        dailyEnergyTitle = "ЭНЕРГИЯ ДНЯ",
        strengthTitle = "СИЛА",
        tensionTitle = "НАПРЯЖЕНИЕ",
        guidanceTitle = "НАПРАВЛЕНИЕ",
        dailyGuidanceTitle = "СОВЕТ ДНЯ",
        narrativeTitle = "НАРРАТИВ",
        cardALabel = "Карта A",
        cardBLabel = "Карта B",
        sunSignLabel = "☀ Солнечный знак",
        moonLabel = "🌙 Луна",
        risingLabel = "⤴ Асцендент",
        selectPlaceholder = "Выбрать",
        unspecifiedOption = "Не указывать",
        closeCta = "Закрыть",
        requiredSunSignsError = "Солнечный знак обязателен для обоих",
        genericGenerateError = "Не удалось создать чтение синастрии",
        depthBasic = "Базовое чтение",
        depthPartial = "Расширенное чтение",
        depthComplete = "Полное чтение",
        dimensionAttraction = "Притяжение",
        dimensionEmotional = "Эмоциональный резонанс",
        dimensionCommunication = "Коммуникация",
        dimensionGrowth = "Потенциал роста",
        axisHarmony = "Гармония",
        axisIntensity = "Интенсивность",
        axisStability = "Стабильность",
        axisTransformation = "Трансформация",
        axisCalm = "Спокойствие",
        axisMovement = "Движение",
        axisHarmonyIntensityTitle = "Гармония ↔ Интенсивность",
        axisHarmonyIntensityDescription = "Показывает, течёт ли сегодня связь из баланса и лёгкости или из более яркой эмоциональной искры.",
        axisStabilityTransformationTitle = "Стабильность ↔ Трансформация",
        axisStabilityTransformationDescription = "Показывает, благоприятствует ли энергия дня сохранению построенного или открывает изменения и пересмотр договорённостей.",
        axisCalmMovementTitle = "Спокойствие ↔ Движение",
        axisCalmMovementDescription = "Отражает, лучше ли сделать ставку на паузу и удержание или на большее движение и совместную инициативу.",
    ),
    zodiac = fallbackAppStrings.zodiac.copy(
        aries = "Овен",
        taurus = "Телец",
        gemini = "Близнецы",
        cancer = "Рак",
        leo = "Лев",
        virgo = "Дева",
        libra = "Весы",
        scorpio = "Скорпион",
        sagittarius = "Стрелец",
        capricorn = "Козерог",
        aquarius = "Водолей",
        pisces = "Рыбы",
    ),
)

private val frenchAppStrings = fallbackAppStrings.copy(
    auth = fallbackAppStrings.auth.copy(
        subtitle = "Connecte-toi pour poursuivre ton chemin magique",
        continueWithGoogle = "Continuer avec Google",
        emailLabel = "E-mail",
        passwordLabel = "Mot de passe",
        signIn = "Se connecter",
        signUp = "Créer un compte",
        connecting = "Connexion…",
        googleSignInErrorFallback = "Impossible de se connecter avec Google",
    ),
    onboarding = fallbackAppStrings.onboarding.copy(
        profileTitle = "Complète ton profil",
        profileSubtitle = "Nous avons besoin de quelques infos pour personnaliser ton expérience.",
        profileAvatarContentDescription = "Avatar du profil",
        usernameLabel = "Nom d'utilisateur",
        usernameError = "Utilise 3 à 20 caractères : lettres, chiffres, point ou underscore.",
        birthDateLabel = "Date de naissance",
        birthDatePlaceholder = "AAAA-MM-JJ",
        birthDateFormatError = "Format invalide. Utilise AAAA-MM-JJ.",
        continueButton = "Continuer",
    ),
    settings = fallbackAppStrings.settings.copy(
        subtitle = "Gère ton profil et tes préférences",
        refreshProfile = "Actualiser le profil",
        signOut = "Se déconnecter",
    ),
    navigation = fallbackAppStrings.navigation.copy(
        onboardingProfile = "Complète ton profil",
        astrology = "Astrologie",
        birthChart = "Essence natale",
        synastry = "Synastrie",
        profile = "Profil",
        settings = "Paramètres",
        oracle = "Oracle",
        guide = "Guide",
        rituals = "Rituels",
        dailyRitual = "Rituel du jour",
        habits = "Habitudes",
        pendulum = "Pendule",
        horoscopeDaily = "Horoscope du jour",
    ),
    common = fallbackAppStrings.common.copy(
        languageSectionTitle = "Langue de l'application",
        languageSectionSubtitle = "Ce changement s'appliquera aux écrans migrés.",
    ),
    profile = fallbackAppStrings.profile.copy(
        defaultUsername = "profil",
        pendingSign = "Signe en attente",
        moonCreditsTitle = "Lunes",
        storeSoon = "Bientôt",
        storeOpen = "Ouvrir",
        birthEssenceEmpty = "Tu n'as pas encore lié ton essence. Nous pouvons t'aider à la découvrir.",
        progressTitle = "Ta progression",
        progressSubtitle = "Chaque petite pratique laisse une trace sur ton chemin.",
        completedCyclesSuffix = "cycles complétés",
        progressNotStarted = "Tu n'as pas encore commencé ce cycle. Complète une pratique dans Habitudes pour faire le premier pas.",
        openHabits = "Ouvrir Habitudes",
        birthEssenceDialogClose = "Fermer",
    ),
    astrologyHome = fallbackAppStrings.astrologyHome.copy(
        headerTitle = "Ton ciel intérieur",
        headerSubtitle = "Explore ton essence et les rythmes qui t'accompagnent",
        horoscopeCardSubtitle = "Ton énergie du jour… et ce qui arrive ensuite",
        birthEssenceCardSubtitle = "L'empreinte de ta naissance",
        synastryCardSubtitle = "L'énergie entre deux",
    ),
    birthChart = fallbackAppStrings.birthChart.copy(
        title = "Essence natale",
        subtitle = "Sélectionne Soleil, Lune et Ascendant pour recevoir une lecture brève style BWitch.",
        sunSignLabel = "Signe solaire",
        moonSignLabel = "Signe lunaire",
        risingSignLabel = "Ascendant",
        discoverLoading = "Découverte...",
        discoverCta = "Découvrir mon essence",
        triadTitle = "Ta triade",
        triadSunLabel = "Soleil",
        triadMoonLabel = "Lune",
        saveLoading = "Enregistrement...",
        saveCta = "Enregistrer dans mon profil",
        shareValidationError = "Génère d'abord une essence valide",
        shareCta = "Partager l'essence",
        syncLoading = "Synchronisation...",
        syncCta = "Synchroniser",
        sharePreviewTitle = "Aperçu du partage",
        shareNowCta = "Partager maintenant",
        shareCancelCta = "Annuler",
        shareFailedFallback = "Impossible de partager l'essence",
    ),
    horoscope = fallbackAppStrings.horoscope.copy(
        refreshLoading = "Actualisation...",
        loading = "Chargement...",
        refreshCta = "Actualiser",
        alreadyUpdatedMessage = "Déjà à jour",
        updatedMessage = "Mis à jour",
        refreshErrorMessage = "Impossible d’actualiser l’horoscope",
        dateLabel = "Date",
        moodLabel = "Humeur",
        luckyNumberLabel = "Nombre chanceux",
        luckyColorLabel = "Couleur chanceuse",
    ),
    synastry = fallbackAppStrings.synastry.copy(
        screenTitle = "Synastrie",
        screenSubtitle = "Explorez la dynamique entre deux signes et découvrez quelles zones du lien s'activent le plus.",
        screenSupportingText = "La lecture combine l'affinité symbolique des signes avec la tonalité énergétique du jour.",
        calculateCta = "Calculer la lecture",
        calculatingCta = "Calcul en cours...",
        resultTitle = "Résultat",
        bondMetricsTitle = "MÉTRIQUES DU LIEN",
        dailyEnergyTitle = "ÉNERGIE DU JOUR",
        strengthTitle = "FORCE",
        tensionTitle = "TENSION",
        guidanceTitle = "GUIDANCE",
        dailyGuidanceTitle = "CONSEIL DU JOUR",
        narrativeTitle = "NARRATIF",
        cardALabel = "Carte A",
        cardBLabel = "Carte B",
        sunSignLabel = "☀ Signe solaire",
        moonLabel = "🌙 Lune",
        risingLabel = "⤴ Ascendant",
        selectPlaceholder = "Sélectionner",
        unspecifiedOption = "Non spécifié",
        closeCta = "Fermer",
        requiredSunSignsError = "Le signe solaire est obligatoire pour les deux personnes",
        genericGenerateError = "Impossible de générer la lecture de synastrie",
        depthBasic = "Lecture essentielle",
        depthPartial = "Lecture élargie",
        depthComplete = "Lecture complète",
        dimensionAttraction = "Attraction",
        dimensionEmotional = "Résonance émotionnelle",
        dimensionCommunication = "Communication",
        dimensionGrowth = "Potentiel de croissance",
        axisHarmony = "Harmonie",
        axisIntensity = "Intensité",
        axisStability = "Stabilité",
        axisTransformation = "Transformation",
        axisCalm = "Calme",
        axisMovement = "Mouvement",
        axisHarmonyIntensityTitle = "Harmonie ↔ Intensité",
        axisHarmonyIntensityDescription = "Indique si le lien circule aujourd'hui dans l'équilibre et la fluidité, ou via une étincelle émotionnelle plus intense.",
        axisStabilityTransformationTitle = "Stabilité ↔ Transformation",
        axisStabilityTransformationDescription = "Montre si l'énergie du jour favorise la consolidation de l'existant ou l'ouverture au changement et à la redéfinition des accords.",
        axisCalmMovementTitle = "Calme ↔ Mouvement",
        axisCalmMovementDescription = "Reflète s'il vaut mieux privilégier la pause et la contenance, ou activer davantage de mouvement et d'initiative partagée.",
    ),
    zodiac = fallbackAppStrings.zodiac.copy(
        taurus = "Taureau",
        gemini = "Gémeaux",
        cancer = "Cancer",
        leo = "Lion",
        virgo = "Vierge",
        libra = "Balance",
        scorpio = "Scorpion",
        sagittarius = "Sagittaire",
        capricorn = "Capricorne",
        aquarius = "Verseau",
        pisces = "Poissons",
    ),
)

private val italianAppStrings = fallbackAppStrings.copy(
    auth = fallbackAppStrings.auth.copy(
        subtitle = "Accedi per continuare il tuo percorso magico",
        continueWithGoogle = "Continua con Google",
        emailLabel = "Email",
        passwordLabel = "Password",
        signIn = "Accedi",
        signUp = "Crea account",
        connecting = "Connessione…",
        googleSignInErrorFallback = "Accesso con Google non riuscito",
    ),
    onboarding = fallbackAppStrings.onboarding.copy(
        profileTitle = "Completa il tuo profilo",
        profileSubtitle = "Ci servono alcuni dati per personalizzare la tua esperienza.",
        profileAvatarContentDescription = "Avatar del profilo",
        usernameLabel = "Nome utente",
        usernameError = "Usa da 3 a 20 caratteri: lettere, numeri, punto o underscore.",
        birthDateLabel = "Data di nascita",
        birthDatePlaceholder = "AAAA-MM-GG",
        birthDateFormatError = "Formato non valido. Usa AAAA-MM-GG.",
        continueButton = "Continua",
    ),
    settings = fallbackAppStrings.settings.copy(
        subtitle = "Gestisci il tuo profilo e le preferenze",
        refreshProfile = "Aggiorna profilo",
        signOut = "Disconnetti",
    ),
    navigation = fallbackAppStrings.navigation.copy(
        onboardingProfile = "Completa il tuo profilo",
        astrology = "Astrologia",
        birthChart = "Essenza natale",
        synastry = "Sinastria",
        profile = "Profilo",
        settings = "Impostazioni",
        oracle = "Oracolo",
        guide = "Guida",
        rituals = "Rituali",
        dailyRitual = "Rituale del giorno",
        habits = "Abitudini",
        pendulum = "Pendolo",
        horoscopeDaily = "Oroscopo giornaliero",
    ),
    common = fallbackAppStrings.common.copy(
        languageSectionTitle = "Lingua dell'app",
        languageSectionSubtitle = "La modifica sarà applicata alle schermate migrate.",
    ),
    profile = fallbackAppStrings.profile.copy(
        defaultUsername = "profilo",
        pendingSign = "Segno in sospeso",
        moonCreditsTitle = "Lune",
        storeSoon = "Presto",
        storeOpen = "Apri",
        birthEssenceEmpty = "Non hai ancora collegato la tua essenza. Ti aiutiamo a scoprirla.",
        progressTitle = "Il tuo progresso",
        progressSubtitle = "Ogni piccola pratica lascia una traccia sul tuo cammino.",
        completedCyclesSuffix = "cicli completati",
        progressNotStarted = "Non hai ancora iniziato questo ciclo. Completa una pratica in Abitudini per fare il primo passo.",
        openHabits = "Apri Abitudini",
        birthEssenceDialogClose = "Chiudi",
    ),
    astrologyHome = fallbackAppStrings.astrologyHome.copy(
        headerTitle = "Il tuo cielo interiore",
        headerSubtitle = "Esplora la tua essenza e i ritmi che ti accompagnano",
        horoscopeCardSubtitle = "La tua energia di oggi… e ciò che arriva",
        birthEssenceCardSubtitle = "L'impronta della tua nascita",
        synastryCardSubtitle = "L'energia tra due persone",
    ),
    birthChart = fallbackAppStrings.birthChart.copy(
        title = "Essenza natale",
        subtitle = "Seleziona Sole, Luna e Ascendente per ricevere una breve lettura in stile BWitch.",
        sunSignLabel = "Segno solare",
        moonSignLabel = "Segno lunare",
        risingSignLabel = "Ascendente",
        discoverLoading = "Scoperta in corso...",
        discoverCta = "Scopri la mia essenza",
        triadTitle = "La tua triade",
        triadSunLabel = "Sole",
        triadMoonLabel = "Luna",
        saveLoading = "Salvataggio...",
        saveCta = "Salva nel mio profilo",
        shareValidationError = "Genera prima un'essenza valida",
        shareCta = "Condividi essenza",
        syncLoading = "Sincronizzazione...",
        syncCta = "Sincronizza",
        sharePreviewTitle = "Anteprima condivisione",
        shareNowCta = "Condividi ora",
        shareCancelCta = "Annulla",
        shareFailedFallback = "Impossibile condividere l'essenza",
    ),
    horoscope = fallbackAppStrings.horoscope.copy(
        refreshLoading = "Aggiornamento...",
        loading = "Caricamento...",
        refreshCta = "Aggiorna",
        alreadyUpdatedMessage = "È già aggiornato",
        updatedMessage = "Aggiornato",
        refreshErrorMessage = "Impossibile aggiornare l’oroscopo",
        dateLabel = "Data",
        moodLabel = "Umore",
        luckyNumberLabel = "Numero fortunato",
        luckyColorLabel = "Colore fortunato",
    ),
    synastry = fallbackAppStrings.synastry.copy(
        screenTitle = "Sinastria",
        screenSubtitle = "Esplora la dinamica tra due segni e scopri quali aree del legame si attivano di più.",
        screenSupportingText = "La lettura combina l'affinità simbolica tra segni con la sfumatura energetica quotidiana.",
        calculateCta = "Calcola lettura",
        calculatingCta = "Calcolo...",
        resultTitle = "Risultato",
        bondMetricsTitle = "METRICHE DEL LEGAME",
        dailyEnergyTitle = "ENERGIA DEL GIORNO",
        strengthTitle = "FORZA",
        tensionTitle = "TENSIONE",
        guidanceTitle = "GUIDA",
        dailyGuidanceTitle = "CONSIGLIO DEL GIORNO",
        narrativeTitle = "NARRATIVA",
        cardALabel = "Carta A",
        cardBLabel = "Carta B",
        sunSignLabel = "☀ Segno solare",
        moonLabel = "🌙 Luna",
        risingLabel = "⤴ Ascendente",
        selectPlaceholder = "Seleziona",
        unspecifiedOption = "Non specificare",
        closeCta = "Chiudi",
        requiredSunSignsError = "Il segno solare è obbligatorio per entrambe le persone",
        genericGenerateError = "Impossibile generare la lettura di sinastria",
        depthBasic = "Lettura essenziale",
        depthPartial = "Lettura ampliata",
        depthComplete = "Lettura completa",
        dimensionAttraction = "Attrazione",
        dimensionEmotional = "Sintonia emotiva",
        dimensionCommunication = "Comunicazione",
        dimensionGrowth = "Potenziale di crescita",
        axisHarmony = "Armonia",
        axisIntensity = "Intensità",
        axisStability = "Stabilità",
        axisTransformation = "Trasformazione",
        axisCalm = "Calma",
        axisMovement = "Movimento",
        axisHarmonyIntensityTitle = "Armonia ↔ Intensità",
        axisHarmonyIntensityDescription = "Indica se oggi il legame scorre da equilibrio e fluidità oppure da una scintilla emotiva più intensa.",
        axisStabilityTransformationTitle = "Stabilità ↔ Trasformazione",
        axisStabilityTransformationDescription = "Mostra se l'energia del giorno favorisce il consolidamento di quanto costruito o l'apertura al cambiamento e alla ridefinizione degli accordi.",
        axisCalmMovementTitle = "Calma ↔ Movimento",
        axisCalmMovementDescription = "Riflette se conviene privilegiare pausa e contenimento oppure attivare più movimento e iniziativa condivisa.",
    ),
    zodiac = fallbackAppStrings.zodiac.copy(
        taurus = "Toro",
        gemini = "Gemelli",
        cancer = "Cancro",
        libra = "Bilancia",
        scorpio = "Scorpione",
        sagittarius = "Sagittario",
        capricorn = "Capricorno",
        aquarius = "Acquario",
        pisces = "Pesci",
    ),
)

private val germanAppStrings = fallbackAppStrings.copy(
    auth = fallbackAppStrings.auth.copy(
        subtitle = "Melde dich an, um deinen magischen Weg fortzusetzen",
        continueWithGoogle = "Mit Google fortfahren",
        emailLabel = "E-Mail",
        passwordLabel = "Passwort",
        signIn = "Anmelden",
        signUp = "Konto erstellen",
        connecting = "Verbinden…",
        googleSignInErrorFallback = "Google-Anmeldung fehlgeschlagen",
    ),
    onboarding = fallbackAppStrings.onboarding.copy(
        profileTitle = "Vervollständige dein Profil",
        profileSubtitle = "Wir benötigen einige Daten, um dein Erlebnis zu personalisieren.",
        profileAvatarContentDescription = "Profilbild",
        usernameLabel = "Benutzername",
        usernameError = "Verwende 3 bis 20 Zeichen: Buchstaben, Zahlen, Punkt oder Unterstrich.",
        birthDateLabel = "Geburtsdatum",
        birthDatePlaceholder = "JJJJ-MM-TT",
        birthDateFormatError = "Ungültiges Format. Nutze JJJJ-MM-TT.",
        continueButton = "Weiter",
    ),
    settings = fallbackAppStrings.settings.copy(
        subtitle = "Verwalte dein Profil und deine Einstellungen",
        refreshProfile = "Profil aktualisieren",
        signOut = "Abmelden",
    ),
    navigation = fallbackAppStrings.navigation.copy(
        onboardingProfile = "Vervollständige dein Profil",
        astrology = "Astrologie",
        birthChart = "Geburtsessenz",
        synastry = "Synastrie",
        profile = "Profil",
        settings = "Einstellungen",
        oracle = "Orakel",
        guide = "Leitfaden",
        rituals = "Rituale",
        dailyRitual = "Tagesritual",
        habits = "Gewohnheiten",
        pendulum = "Pendel",
        horoscopeDaily = "Tageshoroskop",
    ),
    common = fallbackAppStrings.common.copy(
        languageSectionTitle = "App-Sprache",
        languageSectionSubtitle = "Diese Änderung gilt für bereits migrierte Screens.",
    ),
    profile = fallbackAppStrings.profile.copy(
        defaultUsername = "profil",
        pendingSign = "Zeichen ausstehend",
        moonCreditsTitle = "Monde",
        storeSoon = "Bald",
        storeOpen = "Öffnen",
        birthEssenceEmpty = "Du hast deine Essenz noch nicht verknüpft. Wir helfen dir, sie zu entdecken.",
        progressTitle = "Dein Fortschritt",
        progressSubtitle = "Jede kleine Praxis hinterlässt eine Spur auf deinem Weg.",
        completedCyclesSuffix = "abgeschlossene Zyklen",
        progressNotStarted = "Du hast diesen Zyklus noch nicht begonnen. Schließe eine Praxis in Gewohnheiten ab, um den ersten Schritt zu machen.",
        openHabits = "Gewohnheiten öffnen",
        birthEssenceDialogClose = "Schließen",
    ),
    astrologyHome = fallbackAppStrings.astrologyHome.copy(
        headerTitle = "Dein innerer Himmel",
        headerSubtitle = "Erkunde deine Essenz und die Rhythmen, die dich begleiten",
        horoscopeCardSubtitle = "Deine Energie für heute… und was als Nächstes kommt",
        birthEssenceCardSubtitle = "Der Abdruck deiner Geburt",
        synastryCardSubtitle = "Die Energie zwischen zwei",
    ),
    birthChart = fallbackAppStrings.birthChart.copy(
        title = "Geburtsessenz",
        subtitle = "Wähle Sonne, Mond und Aszendent, um eine kurze BWitch-Lesung zu erhalten.",
        sunSignLabel = "Sternzeichen Sonne",
        moonSignLabel = "Sternzeichen Mond",
        risingSignLabel = "Aszendent",
        discoverLoading = "Wird entdeckt...",
        discoverCta = "Meine Essenz entdecken",
        triadTitle = "Deine Triade",
        triadSunLabel = "Sonne",
        triadMoonLabel = "Mond",
        triadAscLabel = "Asz",
        saveLoading = "Speichern...",
        saveCta = "In meinem Profil speichern",
        shareValidationError = "Erzeuge zuerst eine gültige Essenz",
        shareCta = "Essenz teilen",
        syncLoading = "Synchronisieren...",
        syncCta = "Synchronisieren",
        sharePreviewTitle = "Vorschau zum Teilen",
        shareNowCta = "Jetzt teilen",
        shareCancelCta = "Abbrechen",
        shareFailedFallback = "Essenz konnte nicht geteilt werden",
    ),
    horoscope = fallbackAppStrings.horoscope.copy(
        refreshLoading = "Aktualisieren...",
        loading = "Laden...",
        refreshCta = "Aktualisieren",
        alreadyUpdatedMessage = "Bereits aktuell",
        updatedMessage = "Aktualisiert",
        refreshErrorMessage = "Horoskop konnte nicht aktualisiert werden",
        dateLabel = "Datum",
        moodLabel = "Stimmung",
        luckyNumberLabel = "Glückszahl",
        luckyColorLabel = "Glücksfarbe",
    ),
    synastry = fallbackAppStrings.synastry.copy(
        screenTitle = "Synastrie",
        screenSubtitle = "Erkunde die Dynamik zwischen zwei Zeichen und entdecke, welche Bereiche der Verbindung am stärksten aktiviert sind.",
        screenSupportingText = "Die Deutung kombiniert symbolische Zeichen-Affinität mit der täglichen energetischen Tendenz.",
        calculateCta = "Deutung berechnen",
        calculatingCta = "Wird berechnet...",
        resultTitle = "Ergebnis",
        bondMetricsTitle = "BINDUNGSMETRIKEN",
        dailyEnergyTitle = "TAGESENERGIE",
        strengthTitle = "STÄRKE",
        tensionTitle = "SPANNUNG",
        guidanceTitle = "LEITFADEN",
        dailyGuidanceTitle = "TAGESHINWEIS",
        narrativeTitle = "NARRATIV",
        cardALabel = "Karte A",
        cardBLabel = "Karte B",
        sunSignLabel = "☀ Sonnenzeichen",
        moonLabel = "🌙 Mond",
        risingLabel = "⤴ Aszendent",
        selectPlaceholder = "Auswählen",
        unspecifiedOption = "Nicht angeben",
        closeCta = "Schließen",
        requiredSunSignsError = "Das Sonnenzeichen ist für beide Personen erforderlich",
        genericGenerateError = "Synastrie-Lesung konnte nicht erstellt werden",
        depthBasic = "Essenzielle Deutung",
        depthPartial = "Erweiterte Deutung",
        depthComplete = "Vollständige Deutung",
        dimensionAttraction = "Anziehung",
        dimensionEmotional = "Emotionale Resonanz",
        dimensionCommunication = "Kommunikation",
        dimensionGrowth = "Wachstumspotenzial",
        axisHarmony = "Harmonie",
        axisIntensity = "Intensität",
        axisStability = "Stabilität",
        axisTransformation = "Transformation",
        axisCalm = "Ruhe",
        axisMovement = "Bewegung",
        axisHarmonyIntensityTitle = "Harmonie ↔ Intensität",
        axisHarmonyIntensityDescription = "Zeigt, ob die Verbindung heute aus Ausgleich und Leichtigkeit fließt oder aus einem stärkeren emotionalen Funken.",
        axisStabilityTransformationTitle = "Stabilität ↔ Transformation",
        axisStabilityTransformationDescription = "Zeigt, ob die Tagesenergie eher das Erhalten des Aufgebauten unterstützt oder Veränderungen und neue Absprachen öffnet.",
        axisCalmMovementTitle = "Ruhe ↔ Bewegung",
        axisCalmMovementDescription = "Spiegelt, ob Pause und Halt wichtiger sind oder mehr Bewegung und gemeinsame Initiative aktiviert werden sollten.",
    ),
    zodiac = fallbackAppStrings.zodiac.copy(
        taurus = "Stier",
        gemini = "Zwillinge",
        cancer = "Krebs",
        leo = "Löwe",
        virgo = "Jungfrau",
        libra = "Waage",
        scorpio = "Skorpion",
        sagittarius = "Schütze",
        capricorn = "Steinbock",
        aquarius = "Wassermann",
        pisces = "Fische",
    ),
)
